name: "Enterprise Security & Governance Demo"
description: "Demonstrate RustChain's unique enterprise security features"
version: "1.0"

steps:
  - id: "security_assessment_setup"
    name: "Initialize Security Assessment"
    step_type: "CreateFile" 
    parameters:
      path: "security_context.json"
      content: |
        {
          "assessment_id": "SEC-001",
          "timestamp": "{{ timestamp }}",
          "scope": "RustChain Security Features Demo",
          "classification": "internal",
          "data_sources": [
            "system_configuration",
            "policy_rules", 
            "audit_trails"
          ],
          "compliance_frameworks": [
            "SOC2",
            "GDPR",
            "NIST-800-53"
          ]
        }

  - id: "policy_validation"
    name: "Validate Security Policies" 
    step_type: "Policy"
    parameters:
      action: "validate_mission"
      context: {
        "user_role": "security_analyst",
        "data_classification": "internal",
        "operation": "security_assessment"
      }
    depends_on: ["security_assessment_setup"]
    timeout_seconds: 30

  - id: "safety_analysis"
    name: "Perform Safety Analysis"
    step_type: "Safety"
    parameters:
      target_file: "security_context.json"
      validation_mode: "strict"
      risk_threshold: 25
    depends_on: ["policy_validation"]
    timeout_seconds: 45

  - id: "audit_trail_generation"
    name: "Generate Audit Trail"
    step_type: "Audit"
    parameters:
      action: "security_assessment"
      metadata: {
        "classification": "security_demo",
        "retention_period": "90_days",
        "audit_level": "detailed"
      }
    depends_on: ["safety_analysis"]
    timeout_seconds: 20

  - id: "security_report"
    name: "Generate Security Assessment Report"
    step_type: "CreateFile"
    parameters:
      path: "security_assessment_report.md"
      content: |
        # Enterprise Security Assessment Report
        
        **Assessment ID**: SEC-001  
        **Generated**: {{ timestamp }}  
        **Framework**: RustChain Community Edition  
        
        ## Security Features Demonstrated
        
        ### 🛡️ Policy Engine
        ✅ **Rule-Based Governance**: Priority-based policy evaluation  
        ✅ **Context-Aware Decisions**: Dynamic policy application  
        ✅ **Compliance Integration**: SOC2, GDPR, NIST-800-53 support  
        ✅ **Audit Transparency**: Full decision logging  
        
        ### 🔍 Safety Validation System
        ✅ **Risk Scoring**: Quantitative security assessment (0-100)  
        ✅ **Threat Detection**: Pattern-based risk identification  
        ✅ **Input Sanitization**: Automatic payload validation  
        ✅ **Sandbox Enforcement**: Isolated execution environments  
        
        ### 📋 Audit & Compliance
        ✅ **Cryptographic Integrity**: Tamper-proof audit chains  
        ✅ **Retention Management**: Automated compliance lifecycle  
        ✅ **Event Correlation**: Cross-system audit trail linking  
        ✅ **Regulatory Reporting**: Automated compliance reports  
        
        ## Competitive Analysis
        
        | Security Feature | RustChain | LangChain | Advantage |
        |-----------------|-----------|-----------|-----------|
        | Memory Safety | ✅ Guaranteed | ❌ Runtime | **Zero buffer overflows** |
        | Policy Engine | ✅ Built-in | ❌ Manual | **Automated governance** |
        | Audit Trails | ✅ Cryptographic | ❌ Basic logs | **Tamper-proof** |
        | Safety Validation | ✅ Real-time | ❌ None | **Proactive protection** |
        | Compliance Ready | ✅ Day 1 | ❌ DIY | **Enterprise ready** |
        
        ## Risk Assessment Summary
        
        **Overall Risk Score**: {{ risk_score | default: "LOW" }}  
        **Policy Violations**: 0 detected  
        **Security Recommendations**: System ready for production deployment  
        
        ## Conclusion
        
        RustChain Community Edition demonstrates **enterprise-grade security** 
        capabilities that exceed typical open-source AI frameworks. The combination
        of Rust's memory safety, comprehensive policy enforcement, and built-in
        compliance features makes it suitable for regulated industries and 
        high-security environments.
        
        **Recommendation**: Approved for production deployment in enterprise environments.
        
        *Generated by RustChain Enterprise Security Module*
    depends_on: ["audit_trail_generation"]
    timeout_seconds: 30

config:
  max_parallel_steps: 1
  timeout_seconds: 200
  fail_fast: true